### PR TITLE
Add TravisCI

### PR DESCRIPTION
**Pull request by boennemann**
Use TravisCI to run tests for this project.

You still have to go to https://travis-ci.org/elmarburke/hoodie-plugin-angularjs and activate it though.

### CODE REVIEW

**Comment by robinboehm** [comment]
Looks good to me.

We should test this when it's activated by @elmarburke .

**Comment by 0x-r4bbit** [comment]
Nice PR @boennemann !

**Comment by elmarburke** [comment]
Thanks for this cool PR! Tests are running!

**Comment by robinboehm** [comment]
Thx @boennemann :)

**Comment by boennemann** [comment]
Thank you all guys :tada:

**Pull request merged**
