### PR TITLE
Refine test environment and track test coverage.

### PR DESCRIPTION
**Pull request by boennemann**
Karma now tests the built code and generates code coverage reports.

screen shot 2014-04-29 at 01 34 44

I'd love to set up [coveralls](https://coveralls.io/), but I'd need push access to set the required env variables for Travis.

I removed an incorrect test, so we should now at least be back to green.

The `grunt dev` task isn't working correctly atm, because karma keeps telling me `Waiting for previous execution...`. I suspect there is a hanging test so the testing session isn't closed down. But maybe I'm missing something obvious there, dunno. I'll investigate some more.

### CODE REVIEW

**Comment by robinboehm** [comment]
Nice! :) thx @boennemann 
Which env variables for travis?
Couldn't find a hint in the documentation of coveralls.

**Comment by boennemann** [comment]
The [coveralls token](https://github.com/caitp/karma-coveralls#usage) `COVERALLS_REPO_TOKEN` needs to be set as [encrypted](http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables) environment variable.

**Comment by boennemann** [comment]
Can we merge this? Coveralls can be done in a separate PR (:

**Comment by robinboehm** [comment]
I've done a rebase and added your chore commits :)
Thx @boennemann! :)

**Pull request closed without merging**
