### PR TITLE
use gulp for the build

### PR DESCRIPTION
**Pull request by robinboehm**
I'm not sure if this is necessary.
Just a proposal and introduction into an open discussion .
- [x] check which is faster
- [x] find a good bump and commit solution 

_Open discussion ping_ @elmarburke

### CODE REVIEW

**Comment by elmarburke** [comment]
Actually the Grunt File is written in CoffeeScript. At least we should change this file to plain JavaScript.
Gulp is fancy and new, we really should test if it's smaller, faster or nicer.
Could you putt the non gulp stuff (jshint and gitignore) to an other PR? This discussion should only be based on GULP vs GRUNT ;)

**Comment by boennemann** [comment]
I guess this plugin has more serious problems than not using the fanciest build system.

Imho the grunt build isn't optimal in the way it's configured, but it already does the job.
I don't see how using gulp is speeding up anything, as watch only triggers karma.
Speeding up the release a few ms isn't worth the time atm.

**Comment by ajoslin** [comment]
Oh I missed this when I opened #29.  My bad.

@boennemann - well the thing is, Grunt's karma watch task doesn't even work for me! It actually slows down development.

**Comment by robinboehm** [comment]
@ajoslin you mean https://github.com/elmarburke/hoodie-plugin-angularjs/pull/28? :)

**Pull request merged**
