### PR TITLE
Public bower

### PR DESCRIPTION
**Pull request by robinboehm**
This is a pure frontend module.
There is no hoodie-backend extension. 
Should we add this to the public bower registry @elmarburke?

### CODE REVIEW

**Comment by 0x-r4bbit** [comment]
This PR contains a lot of stuff that doesn't belong into this PR. But in general +1 for bower.

**Comment by robinboehm** [comment]
@PascalPrecht thx for the hint. fixed that.

**Comment by elmarburke** [comment]
yup, since this plugin is frontend only it makes sense to put it to bower. But we should take care it's explained when to take bower and when you should take the hoodie plugin.

**Comment by 0x-r4bbit** [comment]
And of course, it's also possible to just define `user/repo.git` as valid endpoint

**Pull request merged**
