### PR TITLE
fix(account): set username to undefined on signout

### LINKED ISSUE #37: Username should be cleared on signout
Currently the code reads:

```
  hoodie.account.on(eventName, function (username) {
    $rootScope.$apply(function () {
      service.username = username;
    });
```

My understanding of Hoodie is that hoodie.account.username is defined if a user is logged in, but the signout event is called with the username of the signing-out user. So once you are signed in, there is no way to clear hoodieAccount.username. I'm guessing this code should check for the signout event and set hoodieAccount.username to null in that case.

I'm fairly new to Hoodie, so I may be wrong. I currently have an Angular app that, once I'm logged in, I can't log out of until I reload and get a fresh scope. Things react fine when I log in and username is assigned an initial value, but it never clears even when hoodie:signout fires.

### PR DESCRIPTION
**Pull request by davidpfahler**
Fixes #37.

I was unable to add tests or run the existing tests against this change, so don't merge right away! Neither Grunt nor Gulp ran without errors, I couldn't test. I ran `npm install` and `bower install` and this is the output I get:

``` bash
$ grunt
Running "concat:dist" (concat) task
File "dist/hoodie.angularjs.js" created.

Running "ngmin:module" (ngmin) task
ngminifying dist/hoodie.angularjs.js

Running "karma:continuous" (karma) task
WARN [reporter]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?
INFO [karma]: Karma v0.10.10 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "/Users/djpfahler/localhost/hoodie-plugin-angularjs/bower_components/jquery/dist/jquery.js" does not match any file.
WARN [watcher]: Pattern "/Users/djpfahler/localhost/hoodie-plugin-angularjs/bower_components/hoodie/dist/hoodie.js" does not match any file.
WARN [watcher]: Pattern "/Users/djpfahler/localhost/hoodie-plugin-angularjs/bower_components/angular/angular.js" does not match any file.
WARN [watcher]: Pattern "/Users/djpfahler/localhost/hoodie-plugin-angularjs/bower_components/angular-mocks/angular-mocks.js" does not match any file.
WARN [preprocess]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?
INFO [PhantomJS 1.9.7 (Mac OS X)]: Connected on socket LhTAT4DEZeP8yjy7Om0a
PhantomJS 1.9.7 (Mac OS X) ERROR
    ReferenceError: Can't find variable: angular
    at /Users/djpfahler/localhost/hoodie-plugin-angularjs/src/_main.js:1
PhantomJS 1.9.7 (Mac OS X) ERROR
    ReferenceError: Can't find variable: angular
    at /Users/djpfahler/localhost/hoodie-plugin-angularjs/src/hoodieAccount.js:1
PhantomJS 1.9.7 (Mac OS X) ERROR
    ReferenceError: Can't find variable: angular
    at /Users/djpfahler/localhost/hoodie-plugin-angularjs/src/hoodieArray.js:1
PhantomJS 1.9.7 (Mac OS X) ERROR
    ReferenceError: Can't find variable: angular
    at /Users/djpfahler/localhost/hoodie-plugin-angularjs/src/hoodieProvider.js:1
PhantomJS 1.9.7 (Mac OS X) ERROR
    ReferenceError: Can't find variable: angular
    at /Users/djpfahler/localhost/hoodie-plugin-angularjs/src/hoodieStore.js:1
PhantomJS 1.9.7 (Mac OS X): Executed 0 of 0 ERROR (0.019 secs / 0 secs)
Warning: Task "karma:continuous" failed. Use --force to continue.
```

``` bash
$ gulp

module.js:340
    throw err;
          ^
Error: Cannot find module 'gulp-bump'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/djpfahler/localhost/hoodie-plugin-angularjs/Gulpfile.js:7:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/Users/djpfahler/.nvm/v0.10.29/lib/node_modules/gulp/bin/gulp.js:108:3)
    at Liftoff.launch (/Users/djpfahler/.nvm/v0.10.29/lib/node_modules/gulp/node_modules/liftoff/index.js:140:6)
    at Object.<anonymous> (/Users/djpfahler/.nvm/v0.10.29/lib/node_modules/gulp/bin/gulp.js:59:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

### CODE REVIEW

**Comment by robinboehm** [comment]
Oh, that looks like chaos in our build! =)

**Comment by robinboehm** [comment]
Sorry for that:

Fix due ddda91d588ea1fc241e9a5e0b791fb6e1379beec

Please rebase to avoid merge commits.

**Comment by davidpfahler** [comment]
@robinboehm 

NPM test is still pointing to grunt:

https://github.com/elmarburke/hoodie-plugin-angularjs/blob/master/package.json#L6

``` shell
$ npm test

> hoodie-plugin-angularjs@0.0.17 test /Users/djpfahler/localhost/hoodie-plugin-angularjs
> grunt

grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

```

Also `gulp test`, which I assume you want me to use, fails as well:

``` shell
$ gulp test
[16:12:39] Using gulpfile ~/localhost/hoodie-plugin-angularjs/Gulpfile.js
[16:12:39] Starting 'karma:dev'...
[16:12:40] Starting Karma server...
INFO [karma]: Karma v0.10.10 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "/Users/djpfahler/localhost/hoodie-plugin-angularjs/bower_components/jquery/dist/jquery.js" does not match any file.
WARN [watcher]: Pattern "/Users/djpfahler/localhost/hoodie-plugin-angularjs/bower_components/hoodie/dist/hoodie.js" does not match any file.
WARN [watcher]: Pattern "/Users/djpfahler/localhost/hoodie-plugin-angularjs/bower_components/angular/angular.js" does not match any file.
WARN [watcher]: Pattern "/Users/djpfahler/localhost/hoodie-plugin-angularjs/bower_components/angular-mocks/angular-mocks.js" does not match any file.
INFO [PhantomJS 1.9.7 (Mac OS X)]: Connected on socket ZkD97K6qw5Tw6p83asHn
PhantomJS 1.9.7 (Mac OS X) ERROR
    ReferenceError: Can't find variable: angular
    at /Users/djpfahler/localhost/hoodie-plugin-angularjs/src/_main.js:9
PhantomJS 1.9.7 (Mac OS X) ERROR
    ReferenceError: Can't find variable: angular
    at /Users/djpfahler/localhost/hoodie-plugin-angularjs/src/hoodieAccount.js:9
PhantomJS 1.9.7 (Mac OS X) ERROR
    ReferenceError: Can't find variable: angular
    at /Users/djpfahler/localhost/hoodie-plugin-angularjs/src/hoodieArray.js:9
PhantomJS 1.9.7 (Mac OS X) ERROR
    ReferenceError: Can't find variable: angular
    at /Users/djpfahler/localhost/hoodie-plugin-angularjs/src/hoodieProvider.js:9
PhantomJS 1.9.7 (Mac OS X): Executed 0 of 0 ERROR (0.019 secs / 0 secs)
[16:12:42] 'karma:dev' errored after 2.13 s
[16:12:42] Error in plugin 'gulp-karma'
karma exited with code 1
```

Please fix tests.

**Comment by elmarburke** [comment]
Hi @davidpfahler,
sorry, we had an error in our package.json. We switch from grunt to gulp some time ago and forget the `$ npm test` thing. Now it should working…

**Comment by elmarburke** [comment]
The changes are now moved to http://github.com/elmarburke/hoodie-plugin-angularjs/tree/pr/38 and added tests. Currently there is something wrong with the tests, @robinboehm will look at this soon!

**Comment by davidpfahler** [comment]
@elmarburke You are correct, L26+27 was an oversight on my part. Can I delete my fork or do you need anything else from me?

**Pull request closed without merging**
